version: '2'

services:

  mailslurper:
    image: gabel/mailslurper
    ports:
      - 25:25
      - 9000:8080
      - 8085:8085
    environment:
      - MAILSLURPER_VERSION=1.13.1
    volumes:
      - ./custom-config.json:/opt/mailslurper/config.json
